# Design: Nightly AI Music YouTube Channel

> **Phase 2 complete.** This document was generated on 2026-05-12 during design. Phase 1 shipped nightly pipeline; Phase 2 (Sprints 1–4) added quality gating, mood colors, SRT, weekly themes, compilation. See [README.md](README.md) for latest run status and [EXECUTION_PLAN.md](EXECUTION_PLAN.md) for completion details.

Generated by office-hours + workflow-architect + plan-eng-review on 2026-05-12
Status: Current (updated 2026-05-14 to reflect Phase 2 completion)
Mode: Builder

## Overview

Redesign the existing nightly AI music pipeline (2 songs/night via MiniMax API → Telegram) into a YouTube channel that auto-generates quality music daily with visualizers. Target: 500 subscribers in 1 month. Transparent about AI origin but focused on quality output.

## Builder Mode Questions

These questions drove the office-hours design session. Builder mode — treating this as a side project with growth targets.

### 1. What's the coolest version of this?

AI-generated music that's actually good — uploaded daily to YouTube with visualizers, showing what's possible. Full YouTube experience: thumbnails, descriptions, playlists, channel branding. The pitch: "AI songs can be good. Here's proof, every day."

### 2. Who is the audience?

Two audiences:
- **Primary:** AI-curious music listeners — people skeptical about AI music who need proof it can be good. They find the channel through YouTube recommendations, music subreddits, and AI discussion forums.
- **Secondary:** AI/tech builders — developers and researchers interested in automated content pipelines. They find the channel through GitHub, Twitter, and technical blog posts about the architecture.

### 3. What's the fastest path to something working?

Extend the existing pipeline (already generating 2 songs/night) with a static visualizer and YouTube upload. Ship Phase 1 in 3-5 days → validate content quality and audience response → then scale to multi-agent architecture. The existing MiniMax API + Telegram pipeline is solid foundation — don't rebuild, extend.

### 4. Who are the competitors and what are they doing?

- **AI music channels on YouTube** — Most upload raw AI generations with no visualizer, no branding, no consistency. Quality is hit-or-miss. None publish daily.
- **Human music curation channels** — High production value but slow release cycles and human-dependent. Not direct competition but sets the quality bar.
- **Gap:** No channel combines consistent daily AI music + professional visualizers + transparent AI origin. That's the lane.

### 5. If this was 10x better, what would it look like?

A fully autonomous music channel: trending chart analysis → multi-song AI generation with animated lyrics videos → auto-clipped YouTube Shorts for every song → cross-posted to Twitter/Bilibili/TikTok → LLM-written video descriptions optimized for discovery → growth analytics that feed back into style selection. 500 subscribers in 1 month, 5,000 in 6 months. A case study for AI content creation that developers reference.

## Premises

1. ✅ The existing MiniMax API + Telegram pipeline works but YouTube needs entirely new infrastructure (visualizer generation + YouTube Data API v3 upload + channel management)
2. ✅ Start with static visualizer (album art + waveform) → iterate toward animated visualizers → eventually full AI music videos. Ship fast, polish later.
3. ✅ 500 subscribers in 1 month requires BOTH consistent daily uploads AND distribution strategy
4. ✅ This needs multiple agents — minimum: music gen, visualizer, YouTube uploader, scheduling coordinator

## Approaches Considered

### Approach A: Minimal Viable (Phase 1 — NOW)

Extend existing pipeline with static visualizer + YouTube upload. 2 songs/night. Use existing MiniMax music gen, add FFmpeg waveform visualizer, YouTube Data API v3 upload with scheduling. Telegram stays. Ships in days.

**Effort:** M (3-5 days) | **Risk:** Low

### Approach B: Multi-Agent YouTube Machine (Phase 2 — AFTER validation)

Coordinator agent → sub-agents: Music Gen (N songs configurable), Visualizer (static → animated), YouTube Uploader (SEO, playlists), Growth Agent (shorts, cross-posts). Config-driven YAML.

**Effort:** L (2-3 weeks) | **Risk:** Low-Med

### Approach C: Content Factory (deferred)

Same as B plus Shorts, community posts, LLM-driven SEO. Maximum reach per song.

## Recommendation: A first, then B

Ship Phase 1 to get content on YouTube ASAP. Validate workflow. Learn what resonates. Then build the multi-agent architecture.

## Architecture Decisions

### Phase 1 (from plan-eng-review)

| # | Decision | Choice |
|---|----------|--------|
| 1 | YouTube OAuth strategy | One-time manual setup → auto-refresh token |
| 2 | Bug fix sequencing | Fix all 10 bugs first, then build YouTube |
| 3 | Module structure | Add inline hooks to nightly_music.py, no refactoring |
| 4 | Upload timing | Schedule for peak hours (6pm SGT) via YouTube API |
| 5 | Dedup (check-duplicate.py) | Integrate dedup into fetch_trending |
| 6 | Telegram delivery | Switch to sendMediaGroup |
| 7 | Log rotation | Monthly file rotation (song-log-YYYY-MM.json) |
| 8 | Test strategy | Unit tests for all modules |
| 9 | Parallel generation | Sequential for Phase 1 (2 songs), async for Phase 2 |

### Phase 2 (Sprints 1–4)

| # | Decision | Choice |
|---|----------|--------|
| 10 | Quality gate | Score 0-10 on 5 dimensions; Hero ≥6 (premium), Standard ≥4 (basic), reject <4 |
| 11 | Song count stays at 2 | Quality gate determines output (0-2 songs/day), not volume |
| 12 | Mood-based colors | 7 mood palettes from lyrics keywords (was static `#FF6B6B\|#4ECDC4`) |
| 13 | SRT on long-form | Full-song lyrics via FFmpeg `subtitles=` filter |
| 14 | Staggered schedule | Hero at 18:00 SGT, Standard at 20:00 SGT, Shorts at 12:00 SGT |
| 15 | Shorts duration | 30s (was 45s — higher retention) |
| 16 | Weekly themes | Day-of-week mood modifiers in prompts (Mon-Sun) |
| 17 | Weekly compilation | Sunday FFmpeg concat from Mon-Sat Hero videos |
| 18 | Pollinations.ai images | Free, keyless image generation for backgrounds + thumbnails |
| 19 | Module structure | New standalone modules (song_quality, weekly_themes, prompt_gen, image_gen, nightly_compilation) |

## Pipeline Architecture (Phase 2)

```
CRON 2am SGT
  │
  ▼
nightly_music.py --date YYYY-MM-DD
  │
  ├── 1. Load config (nightly-music.yaml)
  ├── 2. Create daily dir (YYYY-MM-DD/)
  ├── 3. Fetch trending songs (fetch_trending.py)
  │      └── Dedup against last 7 days (check-duplicate.py)
  ├── 4. Apply weekly theme modifier (weekly_themes.py)    ← Phase 2
  ├── 5. Generate songs (MiniMax API, 2 songs)
  │      └── Save MP3 + TXT to daily dir
  ├── 6. Score song quality (song_quality.py)               ← Phase 2
  │      ├── Hero ≥ 6   → full treatment, 18:00 slot
  │      ├── Standard ≥ 4 → basic treatment, 20:00 slot
  │      └── Reject < 4 → dropped, not uploaded
  ├── 7. Generate image prompt from lyrics (prompt_gen.py)  ← Phase 2
  ├── 8. Download background image (image_gen.py)            ← Phase 2
  ├── 9. Detect mood from lyrics → color palette           ← Phase 2
  ├── 10. Generate visualizers (nightly_visualizer.py)
  │       ├── FFmpeg waveform + mood-colored album art → MP4
  │       └── SRT subtitle overlay on long-form             ← Phase 2
  ├── 11. Generate YouTube Shorts (30s, 9:16)               ← Phase 2
  ├── 12. Upload to YouTube (nightly_uploader.py)
  │       ├── Hero video → scheduled 18:00 SGT
  │       ├── Standard video → scheduled 20:00 SGT
  │       └── Shorts → scheduled 12:00 SGT
  ├── 13. Sync to output/ directory
  ├── 14. Log to song-log.json (monthly rotation)
  └── 15. Telegram delivery (sendMediaGroup, summary + links)
       │
       ▼
  SUNDAY ONLY: nightly_compilation.py                      ← Phase 2
       │
       ├── Read song-log for Mon-Sat Hero videos
       ├── FFmpeg concat with chapter markers
       ├── Generate compilation thumbnail
       └── Upload to YouTube (album-style)
```

## File Structure (Phase 2)

```
nightly-ai-music-youtube/
├── README.md
├── DESIGN.md
├── EXECUTION_PLAN.md                            # Phase 1 + Sprint tracker
├── Phase2_Issues.md                             # Phase 2 issue backlog
├── Phase2_ARCHITECTURE.md                       # Phase 2 architecture reference
├── WORKFLOW-pipeline-phase2.md                  # Phase 2 workflow spec
├── scripts/
│   ├── nightly_music.py           # Pipeline orchestrator
│   ├── nightly_visualizer.py      # FFmpeg waveform + CJK overlay + SRT
│   ├── nightly_uploader.py        # YouTube Data API v3 + OAuth
│   ├── nightly_compilation.py     # Weekly album concat (Sunday)     ← P2
│   ├── minimax_music_api.py       # MiniMax API wrapper (music-2.6)
│   ├── fetch_trending.py          # QQ Music / KKBOX / pool scraper
│   ├── check-duplicate.py         # 7-day dedup helper
│   ├── song_quality.py            # 5-dimension song scoring         ← P2
│   ├── weekly_themes.py           # Day-of-week mood modifiers       ← P2
│   ├── prompt_gen.py              # LLM-based image prompt gen       ← P2
│   └── image_gen.py               # Pollinations.ai image download   ← P2
├── config/
│   └── nightly-music.yaml         # song_count, quality_gate, shorts, themes, compilation
├── output/
│   └── YYYY-MM-DD/
│       ├── 01-title.mp3           # Audio
│       ├── 01-title.txt           # Lyrics
│       ├── 01-title.mp4           # Visualizer video (long-form)
│       ├── 01-title-short.mp4     # YouTube Shorts (9:16)            ← P2
│       ├── 01-title.srt           # Subtitle file                    ← P2
│       └── 01-title-thumb.jpg     # YouTube thumbnail
├── logs/
│   ├── nightly_music.log          # Cron output log
│   └── song-log-YYYY-MM.json     # Monthly song log (rotation)
├── assets/
│   ├── backgrounds/               # Visualizer backgrounds (per-song)
│   └── branding/                  # Channel logo + banner            ← P2
├── docs/
│   ├── GROWTH_STRATEGY.md         # 500-sub growth plan              ← P2
│   └── CHANNEL_ABOUT.md           # YouTube About section            ← P2
├── .gitignore
└── .env.example                   # Template (secrets in ~/.hermes/.env)
```

## Success Criteria

| Metric | Target | Phase 2 Status |
|--------|--------|----------------|
| Subscribers (30 days) | 500 | 🏃 Monitoring |
| Daily uploads | 1-2 per day | ✅ Quality-gated (Hero/Standard/reject) |
| Successful generations | 28/30 days | ✅ Scoring + filtering active |
| YouTube automation | Fully automated (upload, title, desc, tags, thumbnail) | ✅ + Shorts + compilation |
| Visualizer output | Waveform + album art static visualizer | ✅ Mood-colored + SRT overlay |
| Quality gate | Score ≥4 to upload, ≥6 for premium | ✅ Active (5 dimensions) |
| Weekly compilation | Sunday album from Mon-Sat Heroes | ✅ FFmpeg concat with chapters |
| Mood-based colors | 7 palettes from lyrics | ✅ LLM + rule-based detection |

## Distribution Plan

- YouTube channel via YouTube Data API v3
- OAuth: one-time manual consent → auto-refresh token forever
- Upload scheduling: 6pm SGT (peak hours, better first-hour views)
- Existing Telegram notification continues (monitoring channel)
- YouTube upload operational with OAuth auto-refresh (tested 2026-05-12)

## Risks

| Risk | Impact | Mitigation |
|------|--------|------------|
| MiniMax API downtime at 2am | Songs missed | Retry once; skip song on second failure |
| YouTube OAuth token expires | No upload | Auto-refresh handles this; fallback: Telegram alert |
| YouTube API quota exceeded | No upload | 2 songs = 3,400/10,000 units (34%), safe |
| YouTube copyright claim | Channel risk | Channel is transparent about AI origin |
| Output directory write failure | Sync fails | Non-fatal; warn and continue |
| Log file corruption | Data loss | Monthly rotation isolates damage |
| Duplicate YouTube upload | Wasted quota | Idempotent song log prevents re-upload |

## Dependencies

| Dependency | Type | Status |
|------------|------|--------|
| MiniMax API key | Required | ✅ Configured in ~/.hermes/.env |
| Telegram bot token | Required | ✅ Configured in ~/.hermes/.env |
| FFmpeg 6.1.1 | Required | ✅ Installed in WSL |
| Google Cloud Project | Required | ✅ Created, YouTube API enabled |
| YouTube Data API v3 | Required | ✅ Enabled, quota at 10,000 units/day |
| YouTube OAuth consent | Required | ✅ Completed — token at /mnt/d/Hermes/secrets/ |
| CJK font (wqy-zenhei) | Required | ✅ Installed via apt |
| Background images | Required | ✅ default-dark.jpg in assets/backgrounds/ |
| Python deps | Required | ✅ google-auth, google-api-client in ~/.hermes/venv/ |
| OAuth token auto-refresh | Required | ✅ Tested — working on 2026-05-12 run |
| Pollinations.ai API | Required (Phase 2) | ✅ Free, no key — rate-limited to 15s delay |
| mmx CLI | Required (Phase 2) | ✅ MiniMax CLI for LLM prompt generation |
| Pillow (PIL) | Required (Phase 2) | ✅ Python imaging library for thumbnail compositing |

## Phase 2: What We Built

Phase 2 (Sprints 1–4) was implemented 2026-05-14 to 2026-05-14. All features shipped in a single day.

| Sprint | Deliverables | Status |
|--------|-------------|--------|
| **Sprint 1** | Quality gating (`song_quality.py`), mood-based colors (7 palettes), SRT subtitle overlay, staggered Hero/Standard schedule, 30s Shorts | ✅ Complete |
| **Sprint 2** | Pollinations.ai image gen (`image_gen.py`), LLM prompt gen (`prompt_gen.py`), channel branding assets, per-song backgrounds + thumbnails | ✅ Complete |
| **Sprint 3** | Weekly themes (`weekly_themes.py`), day-of-week mood modifiers, config injection | ✅ Complete |
| **Sprint 4** | Weekly compilation (`nightly_compilation.py`), FFmpeg concat with chapter markers, B1–B3 ordering bug fixes, E2E regression | ✅ Complete |

**Pipeline evolution:**
- **Phase 1:** 2 songs → static visualizer → YouTube (18:00) → Telegram
- **Phase 2:** 2 songs → quality score → mood colors → SRT overlay → Shorts → staggered upload (Hero 18:00 / Standard 20:00 / Shorts 12:00) → weekly compilation (Sunday)

## Next Steps

See [EXECUTION_PLAN.md](EXECUTION_PLAN.md) for detailed implementation order and [README.md](README.md) for current status.

## What I noticed about how you think

- "Full YouTube experience" means visualizers, branding, playlists — not just uploading MP3s
- 500 subs in 1 month with a clear strategy split: uploads AND distribution — algorithm-aware
- "A first, then B" chose shipping over chasing shiny architecture — hands-on builder
- "Fix bugs first, then build" — unwilling to build on broken foundations
