"""
MiniMax Music API wrapper — music-2.6 model + lyrics generation.
Verified working 2026-05-05.
Two-step workflow: (1) lyrics_generation API → (2) music_generation API.
"""

import os
import sys
import time
import requests


def _load_api_key():
    """Read MINIMAX_API_KEY from ~/.hermes/.env (no dotenv import needed)."""
    env_path = os.path.expanduser("~/.hermes/.env")
    with open(env_path) as f:
        for line in f:
            if line.startswith("MINIMAX_API_KEY="):
                return line.strip().split("=", 1)[1].strip('"').strip("'")
    raise RuntimeError("MINIMAX_API_KEY not found in ~/.hermes/.env")


# ---------------------------------------------------------------------------
# Lyrics Generation API — Step 1
# ---------------------------------------------------------------------------
LYRICS_URL = "https://api.minimax.io/v1/lyrics_generation"


_PLACEHOLDER_LYRICS_PATTERNS = (
    "[Auto-generated by MiniMax",
    "[Lyrics embedded in audio file]",
)

def _is_placeholder_lyrics(lyrics: str) -> bool:
    """Return True if MiniMax returned a placeholder instead of real lyrics."""
    if not lyrics:
        return True
    return any(lyrics.strip().startswith(p) for p in _PLACEHOLDER_LYRICS_PATTERNS)


def generate_lyrics(prompt):
    """
    Call MiniMax lyrics generation API (Step 1 of the two-step workflow).

    Args:
        prompt: Style/mood description (same as music prompt).

    Returns:
        dict with keys: song_title (str), style_tags (str), lyrics (str)
    """
    api_key = _load_api_key()
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }
    payload = {
        "mode": "write_full_song",
        "prompt": prompt,
    }
    resp = requests.post(LYRICS_URL, json=payload, headers=headers, timeout=60)
    resp.raise_for_status()
    result = resp.json()
    return {
        "song_title": result.get("song_title", ""),
        "style_tags": result.get("style_tags", ""),
        "lyrics": result.get("lyrics", ""),
    }


# ---------------------------------------------------------------------------
# Music Generation API — Step 2
# ---------------------------------------------------------------------------
MUSIC_URL = "https://api.minimax.io/v1/music_generation"


def generate_music(prompt, lyrics="", is_instrumental=False):
    """
    Call MiniMax music-2.6 API and return the JSON result (Step 2).

    Args:
        prompt:          Style/mood description (str)
        lyrics:          Lyrics string with [Verse], [Chorus] tags.
        is_instrumental: Skip vocals if True.

    Returns:
        requests.Response.json() from MiniMax API.
        Keys used: data.audio, extra_info.music_duration, extra_info.music_size.
    """
    api_key = _load_api_key()
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }
    payload = {
        "model": "music-2.6",
        "prompt": prompt,
        "lyrics": lyrics,
        "is_instrumental": is_instrumental,
        "lyrics_optimizer": False,  # We provide lyrics from Step 1
        "audio_setting": {
            "sample_rate": 44100,
            "bitrate": 256000,
            "format": "mp3",
        },
        "output_format": "url",
    }
    resp = requests.post(MUSIC_URL, json=payload, headers=headers, timeout=120)
    resp.raise_for_status()
    return resp.json()


def generate_and_save(prompt, output_path, lyrics="", is_instrumental=False, max_lyrics_retries=2):
    """
    Full two-step pipeline: generate lyrics → generate music → save MP3.
    Downloads immediately (URL expires ~24h).

    RETRY ON PLACEHOLDER LYRICS: if MiniMax returns a placeholder string
    instead of real lyrics, retry up to max_lyrics_retries times before accepting.

    Returns:
        dict with keys: song_title, style_tags, lyrics, audio_url,
                        duration_sec, size_mb
    """
    lyrics_result = None
    generated_lyrics = None
    song_title = ""

    for attempt in range(max_lyrics_retries + 1):
        lyrics_result = generate_lyrics(prompt)
        song_title = lyrics_result["song_title"]
        generated_lyrics = lyrics_result["lyrics"]

        if not _is_placeholder_lyrics(generated_lyrics):
            break

        if attempt < max_lyrics_retries:
            wait = 1 * (attempt + 1)
            print(f"[nightly-music] Placeholder lyrics detected, retrying in {wait}s ({attempt + 1}/{max_lyrics_retries})...", file=sys.stderr)
            time.sleep(wait)
        else:
            print(f"[nightly-music] WARNING: Still getting placeholder lyrics after {max_lyrics_retries} retries. Accepting result.", file=sys.stderr)

    # Retry music generation with exponential backoff for 429/5xx
    music_result = None
    max_music_retries = 3
    for music_attempt in range(max_music_retries + 1):
        try:
            music_result = generate_music(
                prompt=prompt,
                lyrics=generated_lyrics,
                is_instrumental=is_instrumental,
            )
            break
        except requests.HTTPError as e:
            status = e.response.status_code if hasattr(e, 'response') and e.response else 0
            if status in (429, 500, 502, 503, 504) and music_attempt < max_music_retries:
                wait = 2 ** (music_attempt + 1)
                print(f"[nightly-music] Music API {status}, retrying in {wait}s ({music_attempt + 1}/{max_music_retries})...", file=sys.stderr)
                time.sleep(wait)
            else:
                raise
        except (requests.ConnectionError, requests.Timeout) as e:
            if music_attempt < max_music_retries:
                wait = 2 ** (music_attempt + 1)
                print(f"[nightly-music] Music API {type(e).__name__}, retrying in {wait}s ({music_attempt + 1}/{max_music_retries})...", file=sys.stderr)
                time.sleep(wait)
            else:
                raise

    if music_result is None:
        raise RuntimeError("Music generation failed after all retries")

    audio_url = music_result["data"]["audio"]
    duration_ms = music_result["extra_info"]["music_duration"]
    size_bytes = music_result["extra_info"]["music_size"]

    # Download immediately — URL expires in ~24h
    audio_resp = requests.get(audio_url, timeout=60)
    audio_resp.raise_for_status()
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "wb") as f:
        f.write(audio_resp.content)

    return {
        "song_title": song_title,
        "style_tags": lyrics_result["style_tags"],
        "lyrics": generated_lyrics,
        "audio_url": audio_url,
        "duration_sec": round(duration_ms / 1000, 1),
        "size_mb": round(size_bytes / (1024 * 1024), 2),
    }
