#!/usr/bin/env python3
"""
song_quality.py — Song Quality Scoring for ManggoMusicCH

Evaluates each generated song on 5 dimensions and returns a 0-10 score.
Used to gate upload quality — weak songs get rejected before reaching YouTube.

Scoring dimensions:
  - lyrics_length (30%): ≥200 chars = 10, ≥100 = 6, ≥50 = 3, <50 = 0
  - has_chorus (25%): [Chorus] marker or repeated section = 10, else 0
  - duration (20%): 120-210s = 10, 90-120s = 7, 60-90s = 4, <60 = 0
  - placeholder_check (15%): No placeholder text = 10, placeholder = 0
  - vocabulary_richness (10%): unique/total word ratio * 20, capped at 10

Verdict thresholds (configurable):
  - hero >= 6.0  -> premium treatment, 18:00 slot
  - standard >= 4.0 -> standard treatment, 20:00 slot
  - reject < 4.0 -> not uploaded

Usage:
    from song_quality import score_song_quality
    result = score_song_quality({"lyrics": "...", "duration_sec": 180, "title": "..."})
    print(result["total_score"], result["verdict"])
"""

import re
from collections import Counter

PLACEHOLDER_PATTERNS = [
    "[Auto-generated by MiniMax",
    "[Lyrics embedded in audio file]",
]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _extract_lyric_lines(lyrics: str) -> list[str]:
    """Extract non-structure lines (remove [Verse], [Chorus] markers)."""
    return [
        l.strip()
        for l in lyrics.split("\n")
        if l.strip() and not l.strip().startswith("[")
    ]


def _extract_structure_markers(lyrics: str) -> list[str]:
    """Extract all [Section] markers from lyrics."""
    return re.findall(r'\[([^\]]+)\]', lyrics)


def _has_repeated_section(lyrics: str) -> bool:
    """
    Detect likely chorus by checking for repeated line chunks.
    Works when chorus is not explicitly labeled with [Chorus] marker.

    Strategy:
      1. Check 3-line sliding window chunks (strong signal).
      2. Fall back to 2-line sliding window chunks (catches shorter repeats).
    """
    lines = _extract_lyric_lines(lyrics)
    if len(lines) < 4:
        return False

    # Check 3-line chunks (strong chorus indicator)
    if len(lines) >= 6:
        chunks_3 = []
        for i in range(len(lines) - 2):
            chunks_3.append("|".join(lines[i:i + 3]))
        counts_3 = Counter(chunks_3)
        if any(count >= 2 for count in counts_3.values()):
            return True

    # Check 2-line chunks (catches shorter repeated hooks)
    chunks_2 = []
    for i in range(len(lines) - 1):
        chunks_2.append("|".join(lines[i:i + 2]))
    counts_2 = Counter(chunks_2)
    return any(count >= 2 for count in counts_2.values())


# ---------------------------------------------------------------------------
# Dimension scorers
# ---------------------------------------------------------------------------


def _lyrics_length_score(lyrics: str) -> int:
    """Score 0-10 for lyrics length (non-structure text only)."""
    lyric_text = " ".join(_extract_lyric_lines(lyrics))
    lyric_len = len(lyric_text)

    if lyric_len >= 200:
        return 10
    elif lyric_len >= 100:
        return 6
    elif lyric_len >= 50:
        return 3
    else:
        return 0


def _chorus_score(lyrics: str) -> int:
    """Score 0-10: check for [Chorus] marker or repeated sections."""
    structure_markers = _extract_structure_markers(lyrics)
    has_chorus_marker = "[Chorus]" in lyrics or any(
        "chorus" in m.lower() for m in structure_markers
    )
    has_repeated = _has_repeated_section(lyrics)

    return 10 if (has_chorus_marker or has_repeated) else 0


def _duration_score(duration_sec: float) -> int:
    """Score 0-10 for song duration."""
    if 120 <= duration_sec <= 210:
        return 10
    elif 90 <= duration_sec < 120:
        return 7
    elif 60 <= duration_sec < 90:
        return 4
    else:
        return 0


def _placeholder_score(lyrics: str) -> int:
    """Score 0-10: 0 if lyrics start with a placeholder pattern, 10 otherwise."""
    if not lyrics.strip():
        return 0
    cleaned = lyrics.lstrip()
    for pattern in PLACEHOLDER_PATTERNS:
        if cleaned.startswith(pattern):
            return 0
    return 10


def _vocabulary_richness_score(lyrics: str) -> float:
    """Score 0-10 based on unique-word ratio (unique / total * 20, capped at 10)."""
    lyric_text = " ".join(_extract_lyric_lines(lyrics))
    words = lyric_text.split()
    total_words = len(words)

    if total_words == 0:
        return 0.0

    unique_words = len(set(words))
    vocab_ratio = unique_words / total_words
    return min(10.0, vocab_ratio * 20)  # 50% unique = 10/10


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def score_song_quality(
    song_result: dict,
    hero_threshold: float = 6.0,
    standard_threshold: float = 4.0,
) -> dict:
    """
    Score a song's quality for YouTube upload.

    Args:
        song_result: Dict with keys 'lyrics', 'duration_sec', 'title', 'status'.
        hero_threshold: Minimum total score for hero verdict (default 6.0).
        standard_threshold: Minimum total score for standard verdict (default 4.0).

    Returns:
        Dict with keys:
            total_score: float (0-10)
            verdict: "hero" | "standard" | "reject"
            breakdown: dict of per-dimension scores
    """
    lyrics = song_result.get("lyrics", "")
    duration = song_result.get("duration_sec", 0)

    # Calculate dimension scores
    dim_lyrics_length = _lyrics_length_score(lyrics)
    dim_chorus = _chorus_score(lyrics)
    dim_duration = _duration_score(duration)
    dim_placeholder = _placeholder_score(lyrics)
    dim_vocab = _vocabulary_richness_score(lyrics)

    # Weighted total
    total = (
        dim_lyrics_length * 0.30
        + dim_chorus * 0.25
        + dim_duration * 0.20
        + dim_placeholder * 0.15
        + dim_vocab * 0.10
    )

    # Lyrics floor: if lyrics_length score is 0 AND total text < 50 chars,
    # cap at 4.0 (standard max) to prevent near-empty lyrics from hitting hero
    if dim_lyrics_length == 0 and len(lyrics.strip()) < 50:
        total = min(total, 4.0)

    # Verdict
    if total >= hero_threshold:
        verdict = "hero"
    elif total >= standard_threshold:
        verdict = "standard"
    else:
        verdict = "reject"

    return {
        "total_score": round(total, 1),
        "verdict": verdict,
        "breakdown": {
            "lyrics_length": dim_lyrics_length,
            "has_chorus": dim_chorus,
            "duration": dim_duration,
            "placeholder_check": dim_placeholder,
            "vocabulary_richness": round(dim_vocab, 1),
        },
    }
